//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangaUpdatesCheck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MangaUpdatesCheck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author(s).
        /// </summary>
        internal static string ScrapeAuthorHeader {
            get {
                return ResourceManager.GetString("ScrapeAuthorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ScrapeConfirmationText {
            get {
                return ResourceManager.GetString("ScrapeConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist(s).
        /// </summary>
        internal static string ScrapeIllustratorHeader {
            get {
                return ResourceManager.GetString("ScrapeIllustratorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensed (in English).
        /// </summary>
        internal static string ScrapeLicensedEnglishHeader {
            get {
                return ResourceManager.GetString("ScrapeLicensedEnglishHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Publisher.
        /// </summary>
        internal static string ScrapePublisherHeader {
            get {
                return ResourceManager.GetString("ScrapePublisherHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completely Scanlated.
        /// </summary>
        internal static string ScrapeScanlatedText {
            get {
                return ResourceManager.GetString("ScrapeScanlatedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status in Country of Origin.
        /// </summary>
        internal static string ScrapeStatusInCountry {
            get {
                return ResourceManager.GetString("ScrapeStatusInCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Complete).
        /// </summary>
        internal static string ScrapeStatusInCountryComplete {
            get {
                return ResourceManager.GetString("ScrapeStatusInCountryComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ScrapeTypeText {
            get {
                return ResourceManager.GetString("ScrapeTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string ScrapeYearText {
            get {
                return ResourceManager.GetString("ScrapeYearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.mangaupdates.com/series.html.
        /// </summary>
        internal static string SeriesSearchUri {
            get {
                return ResourceManager.GetString("SeriesSearchUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manga.
        /// </summary>
        internal static string SeriesTypeManga {
            get {
                return ResourceManager.GetString("SeriesTypeManga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novel.
        /// </summary>
        internal static string SeriesTypeNovel {
            get {
                return ResourceManager.GetString("SeriesTypeNovel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.mangaupdates.com/series.html?id={0}.
        /// </summary>
        internal static string SeriesUriFormat {
            get {
                return ResourceManager.GetString("SeriesUriFormat", resourceCulture);
            }
        }
    }
}
